name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: CompeyDev/setup-rokit@1d9390883f7ebce19d48f5b8d006e11d387c92ab # v0.2.1
        with:
          version: v1.2.0

      - name: Validate skills
        run: lute run test

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: CompeyDev/setup-rokit@1d9390883f7ebce19d48f5b8d006e11d387c92ab # v0.2.1
        with:
          version: v1.2.0

      - name: Setup Lute typedefs
        run: lute setup

      - name: Analyze
        run: lute run analyze
